
################################################################################    
#    Tasking Rest Actions
################################################################################    

tasking_start:
    path:     /start
    defaults: { _controller: SplashTaskingBundle:Actions:start }

tasking_test:
    path:     /test
    defaults: { _controller: SplashTaskingBundle:Actions:test }

