
################################################################################    
#    Tasking Rest Actions
################################################################################    

tasking_start:
    path:     /start
    defaults: { _controller: Splash\Tasking\Controller\ActionsController::startAction}

tasking_test:
    path:     /test
    defaults: { _controller: Splash\Tasking\Controller\ActionsController::testAction }

