
################################################################################    
#    Tasks Controller Demo Display Page
################################################################################    

tasking_controller_demo:
    path:     /list/{Key1}/{Key2}
    defaults:
        _controller:    FrameworkBundle:Template:template
        template:       'SplashTaskingBundle::index.html.twig'
        Key1:           null
        Key2:           null