
################################################################################    
#    Tasking Status
################################################################################    

tasking_status_json_main:
    path:     /tasking
    defaults: { _controller: Splash\Tasking\Controller\StatusController::mainAction }