########################################################################
#   TASKING BUNDLE CONSOLE COMMANDS
########################################################################

services:

    ################################################################################
    # AutoWire for Commands
    Splash\Tasking\Command\:
        resource: '../../Command'
        autowire: true
        tags:    [ 'console.command' ]
