
########################################################################
# TASKING BUNDLE XU LIVE COMPONENTS
########################################################################

services:
    _defaults:
        autowire:           true
        autoconfigure:      true

    ################################################################################
    # AutoWire for UX Live Components
    BadPixxel\Tasking\TwigComponent\:
        resource: '../../TwigComponent'
