
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ########################################################################
    #   PADDOCK TASKING COLLECTORS
    ########################################################################

    Splash\Tasking\Paddock\Collector\:
        resource: '../../Paddock/Collector/'
        tags:    [ 'paddock.collector' ]

    ########################################################################
    #   PADDOCK TASKING EVENTS SUBSCRIBER
    ########################################################################

    Splash\Tasking\Paddock\EventSubscriber\:
        resource: '../../Paddock/EventSubscriber/'
        tags:    [ kernel.event_subscriber ]