# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection:     default
                auto_mapping:   true
                mappings:
                    SplashTaskingBundle: ~
            tasking:
                connection:     default
                mappings:
                    SplashTaskingBundle: ~