
################################################################################    
#    Tasking Rest Actions
################################################################################    

tasking_start:
    path:     /start
    defaults: { _controller: SplashTaskingBundle:Actions:start }

tasking_test:
    path:     /test
    defaults: { _controller: SplashTaskingBundle:Actions:test }

################################################################################    
#    Tasks Index & Display Page Routes
################################################################################    

tasking_list:
    path:     /list
    defaults: { _controller: SplashTaskingBundle:Notify:notify }