
################################################################################    
#    Tasking Rest Actions
################################################################################    

tasking_start:
    path:     /start
    defaults: { _controller: SplashTaskingBundle:Actions:start }

tasking_test:
    path:     /test
    defaults: { _controller: SplashTaskingBundle:Actions:test }

################################################################################    
#    Tasks Controler Demo Display Page
################################################################################    

tasking_controler_demo:
    path:     /list/{Key1}/{Key2}
    defaults:
        _controller:    FrameworkBundle:Template:template
        template:       'SplashTaskingBundle::index.html.twig'
        Key1:           null
        Key2:           null