# Project language
language: php

# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

# Matrix to test in every php version
#matrix:
#  include:
#    - php: 5.5
#    - php: 5.6
#    - php: 7.0
#    - php: 7.1
#    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Versions of PHP to test against
php:
#    - "5.6"
#    - "7.0"
    - "7.1"
#    - "7.2"
    - "hhvm"
    
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        
    matrix:
        - SF_VERSION="2.8.*"
        - SF_VERSION="3.3.*"
        - SF_VERSION="3.4.*"
        - SF_VERSION="4.0.*"  STABILITY="dev" 
        
    allow_failures:
        - env: SF_VERSION="4.0.*"  STABILITY="dev"       
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

before_install:
    # Update composer
    - composer self-update
    # Setup Travis PHP     
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    # Setup Composer Stability if Required   
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    # Setup Symfony Version if Required    
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;
    # Create Database
    - mysql -e 'CREATE DATABASE IF NOT EXISTS symfony;'
      
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    - echo "Build Dependencies"
    - composer update --prefer-dist --no-scripts --no-interaction    
    
    - echo "Configuring The Bundles"
    - cp app/parameters.yml.dist app/parameters.yml
    
    - echo "Install Symfony"
    - php bin/console doctrine:schema:update --force  --no-interaction --no-debug
    
    - echo "Start Web Srever"
    - php bin/console server:start

# Run script
script:
    - php bin/console tasking:check     --env=test
    - php bin/console tasking:start     --env=test
    - php bin/console tasking:check     --env=test
    - phpunit --testdox
    - phpunit

# After a build, send email notification with the build results
#notifications:
#  email: your_email