# Project language
language: php

# Allows use container-based infrastructure
sudo: false
#sudo: required
#dist: trusty

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.cache/pip

# Matrix to test in every php version
#matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
#  fast_finish: true
#  include:
#    - php: 5.5
#    - php: 5.6
#    - php: 7.0
#    - php: 7.1
#    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Versions of PHP to test against
php:
#    - "5.6"
#    - "7.0"
    - "7.1"
#    - "7.2"
    
# Define an environment variable
env:
  - SF_VERSION=""
#  - SF_VERSION="v2.8.31"
#  - SF_VERSION="3.3"

before_install:
# Update composer
  - composer self-update
# Create Database
  - mysql -e 'CREATE DATABASE myapp_test;'    
# Increase memory limit to 4GB  
  - phpenv config-rm xdebug.ini
#  - phpenv config-add build/x_memory.ini
#  - phpenv config-add build/x_errors.ini
  - php -ini | grep memory_limit  

# Install composer dependencies,
# Create database, schema and fixtures
install:   
    - composer create-project symfony/framework-standard-edition symfony $SF_VERSION --prefer-dist --stability=dev --no-scripts
    - cd symfony
#    - composer install --no-interaction --no-scripts --prefer-dist
#    - composer require splash/phpcore:dev-master --no-interaction --no-scripts --prefer-dist
#    - composer require splash/php-bundle:dev-master  --no-interaction --no-scripts --prefer-dist
#    - composer require splash/sylius-bundle:dev-master --no-interaction --no-scripts --prefer-dist
    - echo "Install Splash Tasking Bundles"
    - composer require splash/tasking-bundle:dev-master --prefer-dist --no-interaction --no-scripts
    
    - echo "Configuring Splash Bundles"
    - cp ../Build/parameters.yml.dist app/config/parameters.yml
#    - cp ../build/phpunit.xml.dist phpunit.xml.dist
    - cp ../Build/autoload.php app/autoload.php
    
    - echo "Install Symfony"
    - php bin/console doctrine:schema:update --force --env=test --no-interaction --no-debug
#    - php bin/console sylius:fixtures:load --env=test --no-interaction --no-debug
##    - chmod -R 777 app/autoload.php

    - echo "Enable Splash Bundles"
    - cp  ../Build/AppKernel.php app/AppKernel.php
    - cat ../Build/routing.yml          >> app/config/routing.yml
    
    - echo "Start Web Srever"
    - php bin/console server:start --env=test

# Run script
script:
  - phpunit
  - phpunit

# After a build, send email notification with the build results
#notifications:
#  email: your_email