
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
#
# To us different Versions configured, you need to add hosts to /etc/hosts
#
#    172.201.0.10        dev.tasking.local
#    172.201.0.64        sf6.tasking.local
#    172.201.0.74        sf7.tasking.local
#    172.201.0.84        sf8.tasking.local
#    172.201.0.100       mysql.tasking.local
#    172.201.0.200       phpmyadmin.tasking.local
#
################################################################################

name: "badpixxel-tasking"

################################################################################
# Multi-versions Dev Services
include:
    - docker/database.yaml
    - docker/develop.yaml
    - docker/symfony-6.yaml
    - docker/symfony-7.yaml
#    - docker/symfony-8.yaml        # Waiting for Paddock

################################################################################
# Default Private Network
networks:
    tasking:
        driver: bridge
        ipam:
            config:
                - subnet: 172.201.0.0/24