imports:
    - { resource: services/admin.yml }
    - { resource: services/commands.yml }
    
services:
    
    ########################################################################
    #   TASKING BUNDLE LOW LEVEL SERVICES
    ########################################################################

    ########################################################################
    # Tasks Management Service
    splash.tasking.runner:
        class: Splash\Tasking\Services\Runner
        public:     true        
        arguments:
            - "@service_container"
            - "@logger"
            - "@doctrine.orm.entity_manager"
            - "@splash.tasking.tokens"
            - "%splash_tasking%"
            
    ########################################################################
    # Tasks Management Service
    splash.tasking.tasks:
        class: Splash\Tasking\Services\TasksManager
        public:     true        
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@logger"
            - "@splash.tasking.tokens"
            - "%splash_tasking%"
        tags:
            - { name: kernel.event_listener, event: tasking.add, method: onAddAction }
            - { name: kernel.event_listener, event: tasking.insert, method: onAddAction }

    ########################################################################
    # Supervisor Management Service
    splash.tasking.supervisors:
        class: Splash\Tasking\Services\SupervisorsManager
        public:     true        
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"
            - "@splash.tasking.process"
            - "%splash_tasking%"
        tags:
            - { name: kernel.event_listener, event: tasking.check, method: checkSupervisor }
            - { name: kernel.event_listener, event: tasking.add, method: checkSupervisor }

    ########################################################################
    # Workers Management Service
    splash.tasking.workers:
        class: Splash\Tasking\Services\WorkersManager
        public:     true        
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"
            - "@splash.tasking.process"
            - "%splash_tasking%"

    ########################################################################
    # Tokens Management Service
    splash.tasking.tokens:
        class: Splash\Tasking\Services\TokenManager
        public:     true        
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"
            - "%splash_tasking%"

    ########################################################################
    # Process Management Service
    splash.tasking.process:
        class: Splash\Tasking\Services\ProcessManager
        public:     true        
        arguments:
            - "@logger"
            - "%kernel.root_dir%"
            - "%splash_tasking%"
        tags:
            - { name: kernel.event_listener, event: tasking.add, method: checkCrontab }
         
    