services:

    _defaults:
        autowire:       true
        autoconfigure:  true
        tags:
            - { name: monolog.logger, channel: Tasking }

    ################################################################################
    # AutoWire for Actions
    BadPixxel\Tasking\Actions\:
        resource: '../../Actions'
        tags: ['controller.service_arguments']

    ################################################################################
    # AutoWire for Commands
    BadPixxel\Tasking\Command\:
        resource: '../../Command'

    ################################################################################
    # AutoWire for Event Listeners
    BadPixxel\Tasking\EventListener\:
        resource: '../../EventListener'

    ################################################################################
    # AutoWire for Services
    BadPixxel\Tasking\Services\:
        resource: '../../Services'

    ########################################################################
    # Process Management Service
    BadPixxel\Tasking\Services\ProcessManager:
        tags:
            - { name: kernel.event_listener, event: Splash\Tasking\Events\AddEvent, method: checkCrontab }
            - { name: monolog.logger, channel: Tasking }
