imports:
    - { resource: parameters.yml }

# Framework Configuration
framework:
    translator:      { fallbacks: ["%locale%"] }
    router:
        resource: "routing.yml"
        
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection:     default
                auto_mapping:   true
                mappings:
                    SplashTaskingBundle: ~
            tasking:
                connection:     default
                mappings:
                    SplashTaskingBundle: ~

monolog:
    handlers:
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']  

splash_tasking:
    entity_manager: tasking

services:
    
    # default configuration for services in *this* file
    _defaults:
        autowire:       false    
        autoconfigure:  false    
        public:         false   
        
    
    Tasking.Sampling.Service:
        class: Splash\Tasking\Tests\Services\TasksSamplingService
        public:         true