
parameters:
    
    database_driver:        pdo_mysql
    database_host:          127.0.0.1
    database_port:          null
    database_name:          bundles_tasking_test
    database_user:          root
    database_password:      LIKORN33
        
    kernel.secret:          ThisIsNotASecretKey
    
    locale: en_US
    locales:
        - en_US
        - fr_FR
