
################################################################################
# SPLASH Tasking Bundle
splash_tasking_bundle:
    resource: "@SplashTaskingBundle/Resources/config/routing.yml"
    prefix:   /  